services:
    app:
        build:
            target: dev
        image: boilerplate:development
        container_name: boilerplate_development
        restart: unless-stopped
        volumes:
            - ./backend:/src